#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/cubcloud ~/school ~/personal ~/.config ~/Documents ~/Downloads ~/.reminders/ -mindepth 0 -maxdepth 2 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)

# Create the session if it doesn't exist
if ! tmux has-session -t="$selected_name" 2> /dev/null; then
    tmux new-session -ds "$selected_name" -c "$selected"
fi

# Always enter the session
if [[ -z "$TMUX" ]]; then
    # Not inside tmux → attach
    tmux attach-session -t "$selected_name"
else
    # Already inside tmux → switch client
    tmux switch-client -t "$selected_name"
fi
